apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  version: 1.7.2
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  namespace: cert-manager
  releaseName: cert-manager

resources:
- certmanager-clusterissuer.yaml
